services:
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - appnet

  api:
    build: .
    container_name: flask-api
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    volumes:
      - .:/app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  neo4j_data:
